version: '3'
services:
    base_php:
        container_name: base-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - base
        depends_on:
            - base_db

    base_nginx:
      container_name: base-nginx
      hostname: nginx
      image: nginx:1.19
      restart: unless-stopped
      depends_on:
        - base_php
      ports:
        - '${APP_PORT:-80}:80'
      volumes:
        - .:/var/www/html
        - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf
      networks:
        - base

    base_db:
        container_name: base-db
        image: 'mariadb:10.5.8'
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'basemysql:/var/lib/mysql'
        networks:
            - base
networks:
    base:
        driver: bridge
volumes:
    basemysql:
        driver: local
